[package]
name = "pr_summary"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.44"
tokio = { version = "1.12.0", features = ["macros", "rt"] }
clap = { version = "4.4.18", features = ["derive", "env"] }
octocrab = "0.33.1"
chrono = "0.4.31"
serde_json = "1.0.111"